### ISSUE TITLE
Add property filter to deleteObjects

### ISSUE THREAD

**Issue by lrochette** [electric-cloud/EC-Admin#100]
deleteObjects does not honor the"doNotDelete" property as jobsCleanup

Evaluate this feature and its impact on backward compatibility

**Comment by lrochette** [comment]
@NoelS000, how do you want the filter to be? 

1. inclusive (delete only the objects whose names match the filter if it exists) or, 
2. exclusive (do not delete the objects who match the filter)

Case 2 would match jobsCleanup but I find case 1 to be better as it allows you to create multiple schedules. Using multiple schedules with case 2 is impossible as they would conflict

**Comment by noels00** [comment]
The way that I looked at the property is that it was a property that you could set on jobs that you wanted to save, so that the deleteObjects would not delete those jobs.  For example, for a Release that goes to production, I may want to set the property on all of the jobs for that release, so when I delete everything else during the time frame that the job(s) occurred, it would delete everything but all of the jobs associated with that Release.  That being said though, with the Pipelines, and Deploy, and everything else, it would be more difficult to tag all of the jobs associated with it for saving...

Perhaps it would be better to filter on job names instead of a property.  I would think that #1 would be better for the reason that you suggest, BUT depending on naming conventions, that could be dozens and dozens of cleanup jobs that would be needed for those with tons of products, if they use the product name in their job names.

**Comment by lrochette** [comment]
Sorry my mistake, I read your issue  as a request to add a pattern matching
I'll implement that first

Then there is a new request for pattern matching
At some point, EC-Admin may not be the perfect fit and the customer can always "copy" and modify any of EC-Admin procedure to rewrite for their own need.
