### ISSUE TITLE
Include a help tip for custom "olderThan" values

### ISSUE THREAD

**Issue by kmcknight** [electric-cloud/EC-Admin#121]
Currently the "olderThan" parameter uses a drop down menu, which has reasonable defaults. For special cases, like when first cleaning up a system that's never had the luxury of ec-admin, the ability to specify the value can be very handy (e.g. I want to delete jobs older than 11 months, then 10 months, then select standard 6 month value from drop down).  

This can be easily accomplished by selecting the "switch to property view" when running the procedure, so that the drop down menu now becomes an open field. The user an then enter any day value desired. Since this isn't so obvious, adding a tip in the label for the "Delete jobs older than" parameter would be very helpful.

**Comment by lrochette** [comment]
Give me the tooltip you want (your English is better) and I"ll fix it, assuming I still have a EC VM I can use.

**Comment by kmcknight** [comment]
Lol. Cool. How about something like this:
To specify a custom value, use the "Switch to property view" icon located on the right hand side of the page, then type in the number of days desired.

**Comment by lrochette** [comment]
This is normal behavior of any parameter panel (not GWT), I'm not sure we need a specific tip (or all should have it).
Better documentation or training from the PS team :)

Maybe a good compromise would be to add that tip in the plugin help page

**Comment by kmcknight** [comment]
Yeah, users should know about the "switch to property view", but a lot of them don't. I like the idea of putting a tip in the help page.

**Comment by noels00** [comment]
Laurent, we don’t do a lot of EC-Admin training in the new Flow training – since it only works on the platform objects. The people who use it most now are the Commander folks who have been with us for some time, or those doing a cleanup for an upgrade



Noël Seaton, Professional Services Manager
408-836-5397 | nseaton@electric-cloud.com<mailto:nseaton@electric-cloud.com>
[cid:image004.jpg@01D3C69E.65602AD0]<http://electric-cloud.com/>
website<http://electric-cloud.com/>  |  blog  <http://electric-cloud.com/blog> |  twitter<http://twitter.com/electriccloud> | linkedin<https://www.linkedin.com/company/electric-cloud>
